import { readFileSync, writeFileSync } from "node:fs";
import { createHmac } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
const env = Object.fromEntries(readFileSync(".env.local","utf8").split("\n").filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const i=l.indexOf("=");return[l.slice(0,i).trim(),l.slice(i+1).trim()];}));
const BASE="https://slideshowai-three.vercel.app", out=process.argv[2];
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
const admin=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SECRET_KEY,{auth:{persistSession:false}});
const {data:ss}=await admin.from("slideshows").select("id").order("created_at",{ascending:false}).limit(1).single();
console.log("waiting 160s for Vercel rebuild...");
await sleep(160000);
const pos=1, exp=Math.floor(Date.now()/1000)+7200;
const token=createHmac("sha256",env.TIKTOK_CLIENT_SECRET).update(`${ss.id}:${pos}:${exp}`).digest("hex");
const r=await fetch(`${BASE}/api/tiktok/img/${ss.id}/${pos}?token=${token}&exp=${exp}&cb=${Date.now()}`);
const buf=Buffer.from(await r.arrayBuffer());
writeFileSync(out,buf);
console.log("fetched", buf.length, "bytes ->", out);
